<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-04-28 19:07
=======
# Generated by Django 6.0.4 on 2026-04-26 14:35
>>>>>>> 4eebb01fb12689a7bc161a70b2d75f13ae88af26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
