# Generated by Django 6.0.4 on 2026-04-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=2500)),
                ('rtsp_url', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
